name: Build and Deploy Blazor App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./Main/Application/Application.WebApp/Application.WebApp.csproj

      - name: Build 
        run: dotnet build ./Main/Application/Application.WebApp/Application.WebApp.csproj --configuration Release --no-restore

      - name: Publish 
        run: dotnet publish ./Main/Application/Application.WebApp/Application.WebApp.csproj --configuration Release --output ./publish